/* generated by tools/linux_msvc_semantics.py - do not edit */
#ifndef __HALO_LINUX_MSVC_SEMANTICS_H
#define __HALO_LINUX_MSVC_SEMANTICS_H

/* ---------- file-scope struct and union tags */


/* ---------- COMDAT inline functions */

#pragma weak D3DDevice_SetRenderState
#pragma weak D3DXMatrixIdentity

#endif
